### ISSUE TITLE
Update npm with latest release version

### ISSUE THREAD

**Issue by markmhx** [blockstack/connect#107]
Currently [the latest version on GitHub is v5.0.5](https://github.com/blockstack/connect/releases):

![image](https://user-images.githubusercontent.com/28991/117429320-3acc8780-af27-11eb-8a3c-2d46f8541e61.png)

But [npm is showing and installing v4.3.18](https://www.npmjs.com/package/@stacks/connect):

![image](https://user-images.githubusercontent.com/28991/117429350-4455ef80-af27-11eb-8292-5fb5cec01c2b.png)

![image](https://user-images.githubusercontent.com/28991/117429375-4a4bd080-af27-11eb-9046-ded241195a62.png)

**Comment by hstove** [comment]
I think we can close this. `@stacks/connect` [latest version](https://www.npmjs.com/package/@stacks/connect) is 5.1.0
