### ISSUE TITLE
Unable to close modal if wallet not installed

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/connect#120]
Right now I'm using version `2.0.3.918` in Brave from the [Hiro download page](https://www.hiro.so/wallet/install-web), but I have it set to only activate once I click on the extension. I noticed that when I do not have the extension enabled, which should be the same as not having it installed, I get presented with this screen:

![Screenshot from 2021-04-19 13-21-45](https://user-images.githubusercontent.com/9038904/115298399-48ee6b80-a112-11eb-9fcd-beeba90898ab.png)
*(example from Friedger's [pool registry](https://stacks-pool-registry.pages.dev/), but have experienced the same issues on other sites as well)*

From there, clicking the X or clicking outside the modal does not close it, and I am forced to refresh the page. This is happening in Firefox as well.

I don't see anything in the console logs, but under Manage Extensions in Brave, an error is listed a few times:

```
No hasRehydratedVault, rendered null

Context
popup.html#/sign-up?authRequest=(removed)

Stack Trace
index.js:930 (anonymous function)

Line 930
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

Can provide more detail if needed.

**Comment by aulneau** [comment]
@fbwoolf this would be a good issue to work on after your `onCancel` work
