### ISSUE TITLE
Todos app tutorial won't launch connect window

### ISSUE THREAD

**Issue by pgray-hiro** [blockstack/connect#123]
If you pull down the https://www.github.com/blockstack/todos repository, once you get the application building, the `Get Started` button does not launch the connect window.  The app does not crash and there are no errors in the console.  I troubleshooted this with @aulneau in person, but we were unable to solve on the Zoom.  Recording this issue for tracking.

**Comment by pgray-hiro** [comment]
cc @markmhx @andresgalante

**Comment by markmhx** [comment]
I spoke with @andresgalante about this and we were thinking that @fbwoolf may be able to take this on immediately after her current set of priorities, especially since she has some initial exposure to Connect already given other changes.

I'm assigning to her and placing in the UserX backlog with that in mind.

**Comment by fbwoolf** [comment]
@pgray-hiro I can't seem to repro this anymore, can you? It may have been an issue with just needing to update the chrome web wallet? I think I was having the same issue with the bns app too at one point, but the bug was resolved with reinstalling the extension. What version are you using?

**Comment by aulneau** [comment]
I think this was related to the positioning bug that existed in the extension and has been fixed. @pgray-hiro please try again and if it works, feel free to close this issue.

**Comment by pgray-hiro** [comment]
Yes, this is fixed for me with the latest version of the Web Wallet.  Closing the issue.
