### ISSUE TITLE
profile_url should be returned with authResponse

### ISSUE THREAD

**Issue by aulneau** [blockstack/connect#127]
The payload that is returned by the extension[ includes `authResponse`](https://github.com/blockstack/connect/blob/main/packages/connect/src/types/auth.ts#L3) which is a jwt that contains the profile_url for the root account, which needs to be used by various apps, but we don't currently expose it anywhere.

We should parse the authResponse token and maybe provide the parsed token in addition to the string.

Here is an example of how to do it:
```ts
import { decodeToken } from 'jsontokens';

export interface AuthResponsePayload {
  private_key: string;
  username: string | null;
  hubUrl: string;
  associationToken: string;
  blockstackAPIUrl: string | null;
  core_token: string | null;
  email: string | null;
  exp: number;
  iat: number;
  iss: string;
  jti: string;
  version: string;
  profile: Profile;
  profile_url: string;
  public_keys: string[];
}

const token = decodeToken(authResponseToken); // authResponse is returned from a successful authentication
const payload = token?.payload;
const authResponse = (payload as unknown) as AuthResponsePayload;
```

This is just a suggestion, but the new response could be:

```ts
export interface AuthResponsePayload {
  private_key: string;
  username: string | null;
  hubUrl: string;
  associationToken: string;
  blockstackAPIUrl: string | null;
  core_token: string | null;
  email: string | null;
  exp: number;
  iat: number;
  iss: string;
  jti: string;
  version: string;
  profile: Profile;
  profile_url: string;
  public_keys: string[];
}

export interface FinishedData {  
  authResponseToken: string;  // old version, just a string
  authResponse: AuthResponsePayload;
  userSession: UserSession;
}
```

cc @fbwoolf @kyranjamie

**Comment by markmhx** [comment]
I believe you mentioned this was needed by @MarvinJanssen for the launch of .BTC, correct?

**Comment by fbwoolf** [comment]
Ok, so I should start this one today?

**Comment by MarvinJanssen** [comment]
@markmhx Currently .BTC does not add such a the profile.json to the zonefile as I was unsure how the profile.json was managed, and by which app. (The Extension I assume.) Also, the app was being built before Atlas was activated. I don't think it would be a lot of effort to add the profile.json link.

**Comment by MarvinJanssen** [comment]
Can some/most of this information not be added to what is returned from `session.loadUserData()`? It is what I have been using to get the profile. The only thing it does not contain is `profile_url`. Also, it looks like `session.getAuthResponseToken()` returns `""` even though it is present in local storage. `session.loadUserData().authResponseToken` is populated like you would expect.

**Comment by aulneau** [comment]
> Can some/most of this information not be added to what is returned from `session.loadUserData()`? It is what I have been using to get the profile. The only thing it does not contain is `profile_url`. Also, it looks like `session.getAuthResponseToken()` returns `""` even though it is present in local storage. `session.loadUserData().authResponseToken` is populated like you would expect.

It can, but that's a different library entirely -- not directly in scope with connect or the extension. This imo was a good first step for exposing the parsed authResponse, and thus the profile_url for the account.

**Comment by MarvinJanssen** [comment]
Ah right! On point.
