### ISSUE TITLE
Fix defineCustomElements

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/connect#138]
This bug surfaced in the wallet test-app, so probably easiest to test there. Currently, on main, the `Sign up` button doesn't do anything bc we removed an import from connect that was causing a test failure. The PR linked to this issue should fix both.

- Test with the test-app in web wallet
- Make sure the wallet is uninstalled
- Click on `Sign up`
- Make sure the install modal launches w/out an error!
- Make sure all tests pass

**Comment by Eshwari007** [comment]
@fbwoolf Can you kindly provide some input on the use cases which I can use for testing the ticket?This will be helpful for me to build the test cases as well.

**Comment by fbwoolf** [comment]
Yep, I can add to the description, np. I put a few test steps on the PR itself but will copy them over.

**Comment by Eshwari007** [comment]
Thank you @fbwoolf
