### ISSUE TITLE
Unable to connect to Mocknet - defaults to Testnet

### ISSUE THREAD

**Issue by grahamulator** [blockstack/connect#160]
When attempting to make contract calls to a local Mocknet, the Web Wallet popup attempts to connect to the public Testnet instead. An issue was created here with more details [here](https://github.com/blockstack/stacks-wallet-web/issues/1590), but this appears to be an issue with an underlying package and not the Web Wallet itself.

I am running Hiro Web Wallet v2.14.0 and am able to successfully connect to a Mocknet with the following packages:
```
    "@stacks/connect": "^6.0.0",
    "@stacks/connect-react": "^11.0.0",
    "@stacks/network": "2.0.0-beta.0",
```
However, when upgrading `@stacks/network` to the latest version of `2.0.1-beta.1`, I experience this issue described above.

**Comment by Eshwari007** [comment]
Tested the url with regtest using test demo app.Test passed
