### ISSUE TITLE
Updates to modal

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/connect#17]
Tab indexes aren't managed properly. This is an accessibility issue.

One possible solution:

Recently noticed [`<dialog>` exists as a HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog).

[It requires a polyfill](https://github.com/GoogleChrome/dialog-polyfill), but wonder if it's worth using to follow along with the HTML spec.

#### thomas edit:
additionally, we should take a look at this, and pull over what we need for a11y support and additional features: https://github.com/chakra-ui/chakra-ui/tree/master/packages/chakra-ui/src/Modal

**Comment by markmhx** [comment]
@aulneau do you want to take over here now that @kyranjamie is OOO?

**Comment by aulneau** [comment]
@markmhx yes
