### ISSUE TITLE
Remove display of confirmation modal

### ISSUE THREAD

**Issue by markmhx** [blockstack/connect#32]

**Comment by markmhx** [comment]
![Screen Shot 2020-02-14 at 16.18.45.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/57d24b21-fa70-4f75-959d-e328f2a82531)

**Comment by markmhx** [comment]
@hstove this is done already correct?

**Comment by hstove** [comment]
Not by me - we removed the final "re-enter secret key" screen from the app, but this is still there.
