### ISSUE TITLE
Add error handling for subdomain registrar failures

### ISSUE THREAD

**Issue by markmhx** [blockstack/connect#46]
Per https://github.com/blockstack/app/issues/97#issuecomment-585250016

**Comment by jasperjansz** [comment]
We can have a generic message for now: https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=6847%3A964

In next releases we can have a more specific message depending on the type of error, or automatically try registering it again without user action

**Comment by hstove** [comment]
Closing, duplicate of https://github.com/blockstack/app/issues/192
