### ISSUE TITLE
Fix host page reflow upon display of intro modal

### ISSUE THREAD

**Issue by markmhx** [blockstack/connect#50]
![Kapture 2020-02-17 at 11 12 40](https://user-images.githubusercontent.com/28991/74644490-a259b400-5176-11ea-9614-5c2139f851f6.gif)

**Comment by kyranjamie** [comment]
It looks like opening the modal injects some global css. See `<html>` element computed properties before and after opening modal:

**Before**
![image.png](https://images.zenhubusercontent.com/5d765e279cf7af0001b78a5e/6453ac0c-2ce4-4f20-918f-5fa6c6bf4830)

**After**
![image.png](https://images.zenhubusercontent.com/5d765e279cf7af0001b78a5e/1d252f43-b1a2-49ea-93d3-62100574462b)

I think this is part of a larger problem that the ui library is injecting global styles. 

![image.png](https://images.zenhubusercontent.com/5d765e279cf7af0001b78a5e/40ebd52b-a368-4163-8dcf-1c032cab0a04)

Why we have a default border colour set on the `*` selector is a particular mystery.
