### ISSUE TITLE
Close modal when clicking outside of it or hitting escape key

### ISSUE THREAD

**Issue by markmhx** [blockstack/connect#51]
![Screen Shot 2020-02-17 at 11.13.48.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/84290d59-35fa-4933-8dcf-d3030bd1ba4e)

**Comment by whoabuddy** [comment]
FYI clicking outside the modal works for me in Vivaldi 2.11.1811.38 (Stable channel) (64-bit) on Linux Mint. Hitting `esc` does not.

However, in doing so the button still displays `Loading...`, and clicking on it still pulls up the modal as expected.

![2 2020-02-19 14 19 30 banter pub 6928fccf8a46](https://user-images.githubusercontent.com/9038904/74888408-16dd5000-533b-11ea-9adb-7685f0c2735e.png)

**Comment by markmhx** [comment]
@whoabuddy Thanks for the Banter report. @hstove can we have Banter show "Get started" again if the user bails from onboarding before completion (from modal display onwards)?
