### ISSUE TITLE
Allow developers to pass a parameter to sign in that displays special guidance for existing users in the app

### ISSUE THREAD

**Issue by markmhx** [blockstack/connect#68]
![image.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/ea6fbef5-4e3b-4ccc-90a1-f3707322d66a)

**Comment by jasperjansz** [comment]
https://www.figma.com/file/aXnNi8MOmN3CDrVwaDXXuqX3/Product?node-id=7269%3A267

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/1fd96b33-365d-4859-a3ad-758f31dc8d1d)

I think this is the only screen we'd have to modify in case they pass that param. We only have to account for existing users who do not have a session (pretty small minority). Those who do have a session will see their ID('s) and get it.

So in case they pass the param we simply modify the text to include the Magic Recovery Code.

**Comment by markmhx** [comment]
@sdsantos how does this design approach look to you?

**Comment by sdsantos** [comment]
That's better yes, at least the terms are similar to what they've read before. I would argue on the "pretty small minority". For multi-platforms apps it's common to be logged in into one platform (Android phone) and not on the other (Web).

As long as already logged in users are able to see their IDs and pick one of them to continue, all good. We would consider migrating our auth to Connect.

**Comment by markmhx** [comment]
To be clear, if users are already logged into your app on a given device, they won't have to go through the signin flow here at all. The session with blockstack.js established before migration should be retained after migration.

Only users who would have been signed out on a given device regardless of the migration will need to go through this new sign in flow. 

> As long as already logged in users are able to see their IDs and pick one of them to continue, all good. We would consider migrating our auth to Connect.

This means that this modal to "see their IDs and pick one of them to continue" will show up for existing users only when:

- They've never used your app on a given device
- They've previously used your app on a device but had subsequently signed out of your app or cleared browser cache
