### ISSUE TITLE
Make React a Peer Dependency

### ISSUE THREAD

**Issue by njordhov** [blockstack/connect#74]
**When rendering the `Connect` component, React fails, reporting _"You might have more than one copy of React in the same app"_.**

The React documentation discusses this error, suggesting a potential cause to be [more than one copy of React in the same app](https://reactjs.org/warnings/invalid-hook-call-warning.html#mismatching-versions-of-react-and-react-dom). It advises: 

> maybe a library you’re using incorrectly specifies react as a dependency (rather than a peer dependency).

This library's [package.json](https://github.com/blockstack/connect/blob/master/package.json) indeed specifies react as a dependency, although also as a peer dependency.

**The fix is to change react (and react-dom) to only be peer dependencies.**

PS: I encountered the same issue when developing the [react-blockstack](https://github.com/njordhov/react-blockstack) library. It was resolved by making React a peer dependency. It also resolves similar issues when using `npm link` during library development and testing.

**Comment by njordhov** [comment]
Addressed in PR #76

**Comment by hstove** [comment]
@aulneau and @kyranjamie , what do you think about `[@rollup/plugin-alias](https://github.com/rollup/plugins/tree/master/packages/alias)` to replace React for Preact in production?

I think this would make sense for non-React apps, but I'm not sure what type of side effects it might have on React apps.

**Comment by kyranjamie** [comment]
I'm not particularly familiar with Preact. Why not just use Preact in development as well? Looking quickly at the docs, we'd need to use `preact/compat` to use it 1:1 with React.

**Comment by hstove** [comment]
Using React in development gives us better error handling, and similar benefits.

You're right about needing `compat` - here is how its setup with webpack: https://github.com/blockstack/ux/blob/ci/semantic-release-workflow/packages/app/webpack.config.js#L58:L58

However, since `tsdx` uses Rollup, that's why I was thinking we'd need a similar Rollup config to alias React/Preact.
