### ISSUE TITLE
Don't Depend on Pop-Up Windows

### ISSUE THREAD

**Issue by njordhov** [blockstack/connect#75]
Pop-up windows are a pain, so no wonder many Firefox users don't allow them, including me. So it is unfortunate that Connect assumes pop-up windows are enabled. Consider making Connect work without pop-up windows.

![image](https://user-images.githubusercontent.com/219448/75138880-2395d700-56a0-11ea-9392-e3488cd1dbb7.png)

**Comment by kyranjamie** [comment]
Thanks for all the feedback @njordhov 

This was in part a security consideration. If we used embedded iframes, we'd increase the likelihood of phishing attacks. With a popup, users can at least verify they're interacting with `auth.blockstack.org`.

By default, a lot of browsers block `window.open` _unless_ it's triggered by a click event, which in this case it is. Of course, more strict browser settings do require allowing popups. To the best of our knowledge this is the same as a user trying to authenticate with their Google account, though.

**Comment by markmhx** [comment]
Is there way to popup by default but fall back to loading in the same window if the user has popups disabled in their browser?

**Comment by kyranjamie** [comment]
@njordhov Can you let us know the steps to reproduce the popup block in Firefox? I've done some testing, with block popup option enabled, and it does not get blocked.

As @markmhx suggested, we can detect if a popup is blocked, though, and instead redirect the page to `auth.blockstack.org` like the current browser. Something like:

```typescript
  const newWindow = window.open(url, title, optionsString.join(','));

  if (!newWindow || newWindow.closed || typeof newWindow.closed === 'undefined') {
    document.location.href = url;
  }
```

We need to make some changes to the styles to centre the "popup" within the full browser viewport in instances where pop ups are blocked (it is full width at the moment).
