### ISSUE TITLE
Handle when user ends auth before finished

### ISSUE THREAD

**Issue by aulneau** [blockstack/connect#8]
When the popup is open, and the user does not complete auth, we aren't handling that in connect. We should do something like:
- fire finished() when the component unmounts, and send something to help connect know it was incomplete
- implement a new method for something like onCancel

**Comment by whoabuddy** [comment]
I believe I got caught in this state by mistake and it made for some interesting results.

The full review is [here in the forum](https://forum.blockstack.org/t/try-out-the-new-streamlined-authenticator-with-blockstack-connect-beta/10382/15) with the more relevant parts below.

1. I started to create an account from the "How it works" page, and it never asked me to create an ID (xyz.id.blockstack). Instead, I saw the 12 word phrase and it still let me into the app. Unfortunately, I did not save the phrase as I intended to abandon the process and start over as I typed my review notes.

2. When I went to Get Started from the main page, I saw my raw ID on the list, and created a second new account. I chose overlyverbose.id.blockstack, but after doing so I was prompted for my email address and logged into the app. I was never presented with a Secret Key - but I was able to post and move around as expected.

3. I started completely over again by logging out and closing the tab. Now both the raw ID and overlyverbose show on the login screen, and when creating a new account for lessverbose.id.blockstack, the same thing happened. No secret key was displayed and I was prompted to enter my email for the app.

![image](https://user-images.githubusercontent.com/9038904/74888214-97e81780-533a-11ea-8b83-08dbc49c39ee.png)

So now I have three accounts and no way to access them. :man_shrugging:

**Comment by hstove** [comment]
Hey @whoabuddy, thanks for the comments.

You don't see a new secret key, because all of these IDs are "tied" to a single Secret Key. You don't have different Secret Keys for different usernames.

In terms of losing your secret key - your secret key is still stored locally, so we could build a feature where you can recover your secret key, probably from something like the homepage. We don't have a timeline for that at the moment.

**Comment by markmhx** [comment]
Thanks from me as well @whoabuddy.

> I started to create an account from the "How it works" page, and it never asked me to create an ID (xyz.id.blockstack)

Is it possible you closed out the popup after first opening it and before getting to the username prompt? That seems like the most likely scenario here in having your Secret Key generated – and your session subsequently started – without ever seeing the username prompt.

We don't currently handle the case well when a user starts onboarding but doesn't get to the point of submitting a username. But I've created an issue to track that here: https://github.com/blockstack/app/issues/214

As @hstove mentions, we also don't currently have a way to see your Secret Key again in the app having signed up already. I've created an issue to track that need here: https://github.com/blockstack/app/issues/215

**Comment by whoabuddy** [comment]
@hstove Thank you for the quick reply, that makes more sense now, thank you!

@markmhx Yes, that is definitely possible and likely what happened. I was doing a quick demo while in the middle of typing my notes on the other sections, so I didn't intend to fully sign up, just to show off the basics of the interface. Thank you!
