### ISSUE TITLE
Display guidance for visitors viewing introductory modal with unsupported browser

### ISSUE THREAD

**Issue by markmhx** [blockstack/connect#95]
Any user who views the introductory modal from any browser apart from Chrome or Firefox for desktop should see messaging that requests they change to one of those browsers for continuing by installing the extension there.

Currently we show the same content for all browsers, which leads to a dead-end for visitors with browsers that aren't supported.

## Current screen

![image](https://user-images.githubusercontent.com/28991/113303346-46fa6f00-9301-11eb-9664-9514e7d1460e.png)

**Comment by markmhx** [comment]
@jasperjansz It doesn't appear we have a screen for this case in Figma. Can you produce one, perhaps working with @eugeniadigon here to incorporate a custom illustration as helpful?

**Comment by fbwoolf** [comment]
@jasperjansz I realized when I did the intro modal redesign I didn't handle non-Chrome and FF browsers, so I created this issue: https://github.com/blockstack/connect/issues/143 ...then I saw this one, is there a design for it yet bc I'd like to fix it.

**Comment by jasperjansz** [comment]
@fbwoolf I was actually hoping to handle this in the authentication choice (mobile, extension). But seeing as that's taking a while to build I will make a design that handles this on the extension side too.
